site_name: Matthew Teow
site_url: https://mtyw.github.io
docs_dir: src
site_dir: docs
extra_css:
  - extra.css
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  # Color scheme
  palette: 
  # Palette toggle for light mode
    - scheme: default
      primary: grey grey
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: grey grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # - navigation.tabs
    # - navigation.tabs.sticky
    - toc.follow
    - toc.integrate
extra:
  analytics:
      provider: google
      property: G-CH40M1VTY7
#   generator: false

nav: 
  - Home: index.md